platform :ios, '9.0'

target 'Tipping-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tipping-App

use_frameworks!
pod 'CollapsibleTableSectionViewController', '~> 1.0.0'

end

